meteor-vue/vue-meteor

- packages/vue-component-dev-client/client/dev-client.js
- packages/vue-component-dev-client/package.js
- packages/vue-component-dev-server/package.js
- packages/vue-component-dev-server/server/main.js
Hello, thank you very much for your package.
I believe these changes will resolve #60 and #62.
In order to successfully test on android or ios you will need to run meteor like this
```bash
ROOT_URL=http://${server ip}:${server port}; meteor run android-device ios-device --mobile-server=http://${server ip}:${server port}
```
The reason for this is because the cordova build needs to connect to the server. If the above env vars are not set, the cordova build will look for the server at localhost which will refer to the cordova build and not the server.
With these changes I have successfully tested on an Android device and iOS simulator
> Fix Android and iOS Cordova build

- packages/vue-component-dev-client/client/dev-client.js
- packages/vue-component-dev-server/server/main.js
Simply cleaner. It also supports [CSP](https://en.wikipedia.org/wiki/Content_Security_Policy) out of the box (if one wants to test it in development, though).
> Use Meteor runtime config instead of a custom variable

- packages/vue-component/plugin/dev-server.js
As seen e.g. in
https://github.com/onury/grunt-jasmine-nodejs/issues/20 ,
process.stdout.clearLine doesn't exist when standard output is not a
tty (as is the case when e.g. running inside an IDE).
> Be careful about process.stdout.clearLine not existing

- packages/vue-component/package.js
- packages/vue-component/plugin/tag-handler.js
- packages/vue-component/plugin/vue-compiler.js
This adds support for CSS modules following the implementation used by [vue-loader](https://github.com/vuejs/vue-loader/).
To use CSS modules, you add the `module` attribute to your style tag:
``` css
<style module>
.test {
color: red;
}
</style>
``` 
Then you reference it via the `$style` computed property:
``` js
<div :class="$style.test">Hello!</div>
```
I also fixed a typo on the postcss call ("form" -> "from") since I needed the full path... and then I of course had a typo in that commit message. 😊 
This does not include support for composing from other CSS modules files, since to do that we have to call back to the compiler and either pull the file from cache or compile it on the fly and return the result. We would also have to pull in other file types on demand and process them …
> basic support for css modules via <style module>

- packages/vue-sass/package.js
- packages/vue-sass/vue-sass.js
This addresses the import issue in #76 (imports without file extensions).
If an import is given without a file extension, we will try to find it first as is, then with the .scss extension, then the .sass extension.
If none of those match and the filename didn't start with a `_`, we try again after adding the underscore prefix.
Given the import `@import "foo";`, we will look at the following paths:
```
foo
foo.scss
foo.sass
_foo
_foo.scss
_foo.sass
```
In addition, this PR enables leading slash imports as relative to the Meteor project directory, so `@import "/imports/test.scss"` will be relative to your project instead of your file system.
> Sass imports

- packages/vue-component/plugin/tag-handler.js
Hi, can we add this exception to language type html in template tag? This is because some plugin still use lang="html" although it is same as not using any tag.
For example:
[https://github.com/gluons/vue-highlight.js/blob/master/src/highlight-code.vue](https://github.com/gluons/vue-highlight.js/blob/master/src/highlight-code.vue)
> Add exception to lang="html" as template tag

- README.md
- packages/vue-component/README.md
- packages/vue-component/plugin/tag-handler.js
- packages/vue-component/plugin/vue-compiler.js
I'd like to add support for custom CSS modules compilers similar to your support for custom "lang" processors. If there is no custom processor, it defaults to the basic processor I added in #117.
The main reason for this PR is so I can interop with my css-modules build compiler, allowing the user to import other CSS modules files and use all of the configuration options I provide.
The compile call is identical to the one for lang compilers with the addition of passing in the `styleTag` and sourcemap. I pass in the `styleTag` because I need to set the `autoprefix` attribute to `off` if the user is already using autoprefixer through my package as well as read the `module` attribute so I can implement support for multiple style tags. _I'll need to make another PR eventually since the module …
> enable custom css modules compilers

- packages/vue-component/README.md
- packages/vue-component/plugin/tag-handler.js
- packages/vue-component/plugin/vue-compiler.js
The default variable name (unchanged) is `$style`. Now, the user can control this, and even have separate modules, by setting the value of the module attribute (copying the code example from the updated documentation):
```html
<style module="foo">
.color {
color: orange;
}
</style>
<style module="bar">
.color {
color: purple;
}
</style>
<template>
<div :class="foo.color">Foo Text</div>
<div :class="bar.color">Bar Text</div>
</template>
```
I think that's the last step to put this on par with vue-loader's CSS modules capability.
> Add support for customizing the name of the CSS modules property via the module attribute

- packages/vue-coffee/package.js
- packages/vue-coffee/vue-coffee.js
This PR changes `vue-coffee` to pass *all* CoffeeScript compiler output through Babel, not just when backticks are present. This allows support for CoffeeScript opt-in ES2015 features like modules and generators.
Once this PR is merged in, there will no longer be a need for wrapping [`import` or `export` statements](http://coffeescript.org/#modules) in backticks.
Closes #96.
> Pass all CoffeeScript compiler output through Babel

- packages/vue-sass/vue-sass.js
Some of the latest changes have caused empty `<style>` tags to throw errors. I'm guessing it was caused by https://github.com/Akryum/vue-meteor/commit/68c026d482c0c9fa2c4aa6175764a0f8417988de.
Anyways, after updating from 0.8.15 to the latest, attempting to compile a file with an empty style tag, like either of the following examples, results in the error shown below. This PR addresses this by not preprocessing empty sass/scss files.
I didn't want to completely skip processing all empty `<style>` tags in `tag-handler.js` in case someone created a preprocessor that added content even if the style tag was empty, so I made the adjustment in `vue-sass` instead.
``` html
<style lang="scss"></style>
<style lang="scss">
</style>
```
```
Compiling <style> in lang scss...
[vue-component] Error …
```
> Fix Sass error on empty <style>

- packages/vue-component/plugin/vue-compiler.js
There are quite a few Vue packages on npm where the author doesn't provide a compiled version. This change allows users to load `.vue` files from npm packages, e.g. `import Dropdown from 'vue-my-dropdown';`.
Without this, attempting to import a .vue file from an npm package causes the following error:
```
C:\projects\oss\tests\vue-component-test\node_modules\vue-my-dropdown\src\vue-my-dropdown.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
^
SyntaxError: Unexpected token <
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at …
```
> Enable loading of .vue files from npm packages

- packages/vue-component/plugin/vue-compiler.js
This PR implements lazy-loading for any .vue files that are found in `imports` or `node_modules` directories.
This fixes issues where the .vue files in `imports/` were getting included in the production bundle (#193), and also fixes dynamic imports (#203, #114).
An example project with dynamic imports (not including the vue-component) can be found here: 
https://github.com/nathantreid/vue-component-test/tree/dynamic-import
> implement lazy-loading of components; fixes dynamic imports

- packages/vue-component-dev-server/server/main.js
In one of your recent commits (https://github.com/meteor-vue/vue-meteor/commit/6c5e5ec20798f2d8d880ea5d6d6632d978426db6#diff-26959cdce8f9e9ec2e07c0bac6066129L27), an important feature was rolled back (the ability to control hmr port on the client independently of the server). That feature is essential for single-server setups behind nginx. I've encountered a problem running your demo (https://github.com/meteor-vue/vue-meteor-demo/issues/8) and found a solution: reapply one line from a previous commit (https://github.com/meteor-vue/vue-meteor/commit/e4fbd6a2fde17d368baeb6e2bb3d23d71931edce). It works fine on my server, and since it was already commited by you it should be well-tested. I would be really grateful if you could merge that line back into the project. 
By the way, thanks a lot …
> Re-hotfix HMR port handling

- packages/vue-blaze-template/vue-render-blaze.js
This allows one to also use Blaze Components which override how template resolving happens.
> Use Blaze._getTemplate.

- README.md
There are two bold recommendations for two different projects, which is at first glance very confusing.
The goal of the first recommendation is as a show case, the second recommendation is not recommending the project, but recommending that you should read its readme file.
I would personally prefer the instructions in the same project... but this change is easier to accept.
> Rephrase conflicting recommendation

- packages/vue-component/plugin/dev-server.js
This patch Initializes HMR Dev Server on the same interface specified in meteor run command. Running `meteor run --port=host:port` will bring the meteor server running on interface `host` on port `3000` and HMR Dev Server on port `3003` (default) on the same interface.
> Initializes HMR dev server using the configuration specified in meteor server

- packages/vue-coffee/package.js
- packages/vue-coffee/vue-coffee.js
See https://github.com/meteor/meteor/pull/8960 / https://github.com/meteor/meteor/pull/9018
This PR refactors the `vue-coffee` package to use the new Meteor `coffeescript-compiler` package, which is the “compilation” part of the old Meteor `coffeescript` package split apart from the “build compiler plugin” part. `vue-coffee` using `coffeescript-compiler` lets `vue-coffee` avoid needing to fork the old Meteor `coffeescript` package, and lets `vue-coffee` shrink down to just a few lines of code. This also positions `vue-coffee` to easily respond to new upstream versions of `coffeescript-compiler` (most likely by bumping a dependency version number, with no other changes).
> Refactor vue-coffee

- packages/vue-coffee/README.md
- packages/vue-component/package.js
- packages/vue-component/plugin/regexps.js
- packages/vue-component/plugin/tag-handler.js
- packages/vue-component/plugin/vue-compiler.js
Fixes #165, at least for projects that use `vue-component` (and not the `vue-router` or `vue-router2` Meteor packages, which aren’t used by [vue-meteor-demo](https://github.com/meteor-vue/vue-meteor-demo); I guess the recommended practice now is to use the NPM `vue-router` and not those Meteor packages?).
This PR uses proper module syntax to return modules’ scripts as the scripts for those components. Previously, `vue-component` was doing a find-and-replace on the source code for those components’ scripts, replacing `export default` with `return` before compiling the code. This is unsafe, to say the least, and also incompatible with any code that has already passed through Babel before reaching `vue-component` (such as code processed by `vue-coffee`). Now an extra line is appended to the …
> vue-component: avoid finding and replacing ‘export default’

- packages/vue-component/package.js
- packages/vue-router2/package.js
Updates the babel-compiler package as required to support Meteor 1.6.1. Fixes #290.
> Update babel-compiler for Meteor 1.6.1 compatibility

- packages/vue-component/plugin/tag-handler.js
- packages/vue-component/plugin/vue-compiler.js
CSS modules changes to allow plugins more control
This PR does 2 things:
1. `tag-handler.js` lines 383 - 388 and `vue-compiler.js`: grants CSS modules plugins (i.e. my plugin 😄) the ability to fully control the CSS modules output. Previously, this output was being run through `JSON.stringify` in the compiler, now it's being output directly. This is important for me because the lastest version of my CSS modules plugin has the ability to output a `Proxy` object that displays a helpful error message if the developer attempts to use a class that doesn't exist.
2. `tag-handler.js` lines 446-452: updates the built-in CSS modules code so it still works (no functional changes).
> CSS modules changes to allow plugins more control

- packages/vue-component/plugin/vue-compiler.js
- packages/vue-router/plugin/plugin.js
- packages/vue-router2/plugin/plugin.js
When renaming Vue components, the compiler gets confused because it sees a file with the same source hash and thinks it should be the same, even though it isn't. To reproduce this bug:
1. Clone https://github.com/meteor-vue/vue-meteor-demo
2. Rename `Notes.vue` to `Foo.vue` and adjust the import in `routes.js`. 
3. You will see the following error:
```
W20171209-23:39:12.527(-5)? (STDERR) Error: Cannot find module '/src/imports/ui/Notes.vue'
W20171209-23:39:12.527(-5)? (STDERR)     at makeMissingError (packages/modules-runtime.js:231:12)
W20171209-23:39:12.527(-5)? (STDERR)     at require (packages/modules-runtime.js:241:19)
W20171209-23:39:12.528(-5)? (STDERR)     at src/imports/ui/Notes.vue:22:1
W20171209-23:39:12.528(-5)? (STDERR)     at Foo.vue (src/imports/ui/Notes.vue:22:1) …
```
> Handle file renames properly for Vue components and routes files

- packages/vue-component/plugin/vue-compiler.js
When using CSS modules, a change to the class names causes a change to the `$style` computed property and therefore requires the template to be reloaded in order to take effect. 
For example, if I create the following style, reference it in my template, and save my changes, `$style.foo` won't exist on the client after the hot refresh because the client won't know that it needs to reload the entire compiled JS instead of just reloading the render function.
``` html
<style module>
.foo {
color: red;
}
</style>
<template>
<div :class="$style.foo"></div>
</template>
```
This PR adds cache-checking for the CSS modules output.
> Reload Vue template when CSS modules change in the <style> attribute

- packages/vue-component-dev-client/client/vue2-hot.js
- packages/vue-component/plugin/tag-handler.js
- packages/vue-component/plugin/vue-compiler.js
We've been experiencing hot reload issues for a while, but I hadn't gotten around to reporting it or looking into it. Anyways, there are 2 issues:
1. Sometimes changes don't hot reload and cause the page to refresh instead; (probably #294 and 291)
2. Changes to the script or CSS modules cause the error `Template or render function not defined` (#254)
I dove into it today and now have hot reloads working flawlessly, at least in my limited tests.
Issue 1 is seems to be caused by the change event firing before the file is finished being written. When [the file is read](https://github.com/meteor-vue/vue-meteor/blob/master/packages/vue-component/plugin/vue-compiler.js#L355) sometimes `contents` would be empty, which would then cause HMR to fail and the page would refresh. In my digging, I …
> Hot reload fixes

- packages/vue-ssr/server/index.js
It is currently impossible to append html to `head` or `body` tags using vue-ssr package's `VueSSR.createApp`. In order to allow packages such as [vue-meta](https://github.com/declandewet/vue-meta#step-22-populating-the-document-meta-info-with-inject) to work in SSR, I have made these changes:
- Added the possibility of returning `head` and `body` strings (along with `js` and `app`) which will be appended to their respective tag.
- Added the possibility of returning an `appendHtml` callback allowing to create `head`, `body` or `js` strings after the renderer as generated the app. This is required with [vue-meta](https://github.com/declandewet/vue-meta#step-22-populating-the-document-meta-info-with-inject) which only returns meta once the app as been rendered.
Here is an example of what …
> Add head and body append to vue-ssr createApp

- packages/vue-component/plugin/post-css.js
You can then use `ctx` in a function to know if you have to return configuration for Vue PostCSS or some other: https://github.com/michael-ciniawsky/postcss-load-config#postcssconfigjs-or-postcssrcjs
> Add custom context so that one can identify this configuration

- packages/vue-component/plugin/vue-compiler.js
Currently, the user is forced to use the version of Vue that matches the `vue-template-compiler` package that is bundled with this plugin. If the user has a newer version of Vue, the build crashes with the following error:
```
Vue packages version mismatch:
- vue@2.5.16
- vue-template-compiler@2.5.13
This may cause things to work incorrectly. Make sure to use the same
version for both.
If you are using vue-loader@>=10.0, simply update
vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing
vue-loader/vueify should bump vue-template-compiler to the latest.
```
Rather than force the user to downgrade their `vue` version, this PR enables the user to `npm install` the latest version of the `vue-template-compiler` and `vue-template-es2015-compiler` and have the plugin …
> Enable loading locally installed Vue compiler

- packages/vue-component/package.js
- packages/vue-component/plugin/post-css.js
> Allow loading of PostCSS plugins

- packages/vue-component-dev-client/client/dev-client.js
Otherwise "HRM" in a console looks confusing.
> Isn't it HMR (Hot-Module-Replacement) in everywhere?

- packages/vue-sass/vue-sass.js
Fixes 'Unknown import (file not found)' error when Vue component imports SCSS file that imports another file by relative path.
> Fix imports by relative path in SCSS files

- packages/vue-component-dev-client/client/dev-client.js
- packages/vue-component-dev-client/package.js
- packages/vue-component-dev-server/package.js
- packages/vue-component/README.md
- packages/vue-component/package.js
- packages/vue-component/plugin/vue-compiler.js
- Updated the meteor packages to align with the 1.8 release
- Fixed the continuous reloading issue present in "vue-component-dev-client"
- Added a default babel cache folder value to "process.env.BABEL_CACHE_DIR" so Meteor no longer shows the corresponding warning
> Fixed #326 and updated Meteor packages

- packages/vue-sass/vue-sass.js
Some Packages (for example the `@material/button` packge) has imports relative to node_modules.
These imports previusly failded, because there was no possibility to load these sub-imports.
For the package.json-file:
Add a new snippet like this:
```json
"vue": {
"css": {
"loaderOptions": {
"sass": {
"includePaths": [
"node_modules"
],
}
}
}
},
```
Fixes #246
Fixes #301 
(hopefully)
_this is my first pull-request, so please check carefully and tell me what i've done wrong_
> Config Option for other .scss/.sass import paths.

- packages/vue-component/plugin/vue-compiler.js
This one-line PR fixes #350, where the source maps are offset by the number of lines above the `<script>` opening tag:
(Line 14 is supposed to be highlighted, not line 21. And the brighter-colored line numbers should correspond with the lines where there is source code; picture them shifted up 8 lines each.)
Once this is merged in, not only will `debugger` statements be highlighted on the proper line, but you can also just click on the line number in the gutter in DevTools to set a breakpoint on that line (you know, how it’s supposed to work). Fixes `akryum:vue-coffee` too.
> Fixes #350, makes source maps line up with the correct lines in DevTools

- packages/vue-component-dev-client/client/dev-client.js
- packages/vue-component-dev-client/client/vue2-hot.js
The `_ClientVersions` collection of autoupdate has been replaced by a `_clientVersions` object in Meteor 1.8.1 ( meteor/meteor@13308cf3417e7a0ec23b825f2fcc197ba228686d ).
This pull request will make `vue-component-dev-client` compatible with both versions.
> Introduce client version observer compatible with Meteor 1.8.1

- packages/vue-component/plugin/tag-handler.js
Using class names in the form of `.<vue_component_name>_<local_class_name>__<hash>` (similarly to `vue-loader`) instead of `.vue-module-<hash>-<hash>` should simplify debugging a lot.
> Generate meaningful CSS Modules class names

- packages/vue-component/plugin/vue-compiler.js
See #364 
require behavior has changed in meteor 1.8.2
> [Packages/vue-component] fix: component registration with meteor 1.8.2

- packages/vue-component/package.js
- packages/vue-component/plugin/dev-server.js
- packages/vue-component/plugin/vue-compiler.js
As you may know, we're removing Fibers from Meteor, and this single use of Fibers on this package is breaking tests from Meteor tools.
I was able to test this change locally and it is working. 
Let's review it and publish the new version.
cc @Akryum
> fix: Remove fibers from vue compiler

- packages/vue-component/plugin/tag-handler.js
Some Meteor plugins require to have a `lang="js"` attribute (see https://github.com/Hernanm0g/meteor-vuetify-loader#installation)
But in turn, Vetur does not support this:  https://github.com/vuejs/vetur/blob/master/docs/guide/highlighting.md#syntax-highlighting
**Vetur doc talks about highlighting syntax, but formatting code using Vetur will not work if there is a `lang="js"` for me**
TL;DR:
Figured this being the middle ground would be a good spot to make both things work (auto imports for `meteor-vuetify-loader` as well as code formatting in VScode using Vetur.
> fix: Default `lang` value for `script` blocks
